### ISSUE TITLE
Slow inference

### ISSUE THREAD

**Issue by saadi297** [2U1/Phi3-Vision-ft#4]
I am using serve/cli.py to do inference with original model. I noticed that the inference is too slow but when I replace [this line](https://github.com/2U1/Phi3-Vision-ft/blob/main/src/utils.py#L67C9-L67C95) with `model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)`, where model path is "microsoft/Phi-3-vision-128k-instruct" inference is way faster. Could you please let me know what might be the reason? Thanks

**Comment by 2U1** [comment]
@saadi297 It was caused by the model code, that can handle text-only data.
I've commented the code for now (maybe you are using the code before I commented it.) and it' will be fast as the `AutoModelForCausalLM`.

I'm working on for the code optimization. Will be updated in near future for text-only data training.


BTW, it's just the same code when inference for now,  so you could just use `AutomodelForCausalLM` 

Sorry for the inconvenience.

**Comment by saadi297** [comment]
Thanks for your reply. Yes, I was using the previous code. So the current code does not support text-only training/inference?

**Comment by 2U1** [comment]
Yes is does not support text-only training for now.
I'm working on it.
